### ISSUE TITLE
Supplicate failure: 用户不允许使用本服务! 

### ISSUE THREAD

**Issue by arbaleast** [Superfly12138/rjsupplicant#1]
2020-09-12 10:42:22 Initializing.....
2020-09-12 10:42:23 Lookup the switch...
2020-09-12 10:42:23 Connecting radius server...
2020-09-12 10:42:23 Authenticating now...
2020-09-12 10:42:23 Supplicate failure: 用户不允许使用本服务!

老哥，能指个方向吗？我不懂这个该怎么处理“2020-09-12 10:42:23 Supplicate failure: 用户不允许使用本服务!”

**Comment by Superfly12138** [comment]
> 2020-09-12 10:42:22 Initializing.....
> 2020-09-12 10:42:23 Lookup the switch...
> 2020-09-12 10:42:23 Connecting radius server...
> 2020-09-12 10:42:23 Authenticating now...
> 2020-09-12 10:42:23 Supplicate failure: 用户不允许使用本服务!
> 
> 老哥，能指个方向吗？我不懂这个该怎么处理“2020-09-12 10:42:23 Supplicate failure: 用户不允许使用本服务!”

你是哪个学校的，认证分不分电信，校内等服务？

**Comment by arbaleast** [comment]
湖南工学院，认证的话不大清楚

**Comment by arbaleast** [comment]
试过在windows上用其他学校的客户端登录，有区域限制

**Comment by Superfly12138** [comment]
> 试过在windows上用其他学校的客户端登录，有区域限制

输入-u 用户名 -p 密码 -l
-l可以列出来你们学校的服务
你可以看看你们学校都有什么服务

-u 用户名 -p 密码 -s 服务名
即可

**Comment by arbaleast** [comment]
好的

**Comment by arbaleast** [comment]
sudo ./rjsupplicant.sh -u ×××××× -p ×××××× -l
sysctl: write error: Bad file descriptor
sysctl: write error: Bad file descriptor
sysctl: write error: Bad file descriptor
Version     RG-SU For Linux V1.31
AuthMode    Wired Authentication
Adapter     ×××××××
UserName    ×××××××××
service     1
----------------------------------------
service list[1]  联通
            [2]  校外
            [3]  校内
nic list    [1]* ×××××××
            [2]  ××××××

**Comment by arbaleast** [comment]
这三个服务
2020-09-12 11:11:39 Authenticating now...
2020-09-12 11:11:39 Supplicate failure: 用户不允许使用本服务!
都有这种报错

**Comment by Superfly12138** [comment]
我这是很早之前的版本了，应该是学校锐捷升级了，现在估计不能用了 。

**Comment by arbaleast** [comment]
好吧，麻烦老哥了

**Comment by HUANMVP** [comment]
> 我这是很早之前的版本了，应该是学校锐捷升级了，现在估计不能用了 。

学长吗？还能用吗？😁
