### ISSUE TITLE
认证失败: 不允许使用的客户端类型,请更新锐捷到沈航最新版

### ISSUE THREAD

**Issue by ghitori** [Superfly12138/rjsupplicant#3]
学长您好，我在使用的时候遇到了版本较低的这个问题
请问19年的时候有需要添加什么必要的附加参数吗?
我添加了参数-d 1 -u *** -p *** -n enp2s0 -s 电信
![图片](https://user-images.githubusercontent.com/29966961/221078655-3c6c3df9-9a22-478e-945e-c80717732c80.png)

**Comment by Superfly12138** [comment]
加一个参数 -v 6.84
应该是这样的，指定客户端版本6.84

**Comment by ghitori** [comment]
没有这个参数
`rjsupplicant: invalid option -- 'v'`
好像是mentohust有这个参数，但加了之后也是一样的问题

**Comment by Superfly12138** [comment]
mentohust里应该有一项配置是版本号，如果指定6.84还不可以，那应该需要抓包，把包作为附加项一起认证，做到伪装的目的。我晚上把抓的包传上来

**Comment by ghitori** [comment]
使用[Mentohust-V4](https://github.com/updateing/mentohust-v4)，并添加-v 6.84后依然无法认证，错误相同
我抓包总是有错误，麻烦学长了

**Comment by Superfly12138** [comment]
[DataPackA.mpf](https://github.com/Superfly12138/rjsupplicant/blob/master/DataPackA.mpf) mentohust中配置好附加的文件再次认证试试。

**Comment by lihj0412** [comment]
> 使用[Mentohust-V4](https://github.com/updateing/mentohust-v4)，并添加-v 6.84后依然无法认证，错误相同
> 我抓包总是有错误，麻烦学长了

请问你认证成功了吗？

**Comment by ghitori** [comment]
> 

我明天早上试一下，今天室友有在用，不好测试(我把网线直接插在路由器上了)

**Comment by Superfly12138** [comment]
你问下另一个issue的同学吧，我毕业了都🥺

**Comment by ghitori** [comment]
好的，谢谢学长

**Comment by Superfly12138** [comment]
我在学校的时候用的带mentohust的路由器，一直都能用。

**Comment by ghitori** [comment]
学长是什么时候毕业的啊
我感觉校园网至少三年没更新了，但我还没成功过

**Comment by Superfly12138** [comment]
![88851425-D07D-4F43-8902-04C3EAFF5CFC](https://user-images.githubusercontent.com/23469346/221212319-fc68c449-cb3f-48b9-bbe2-6052c433ee28.jpeg) 使用路由器的可以参考这个，自定义数据文件路径就是我上传的文件，需要放到路由器里，dhcp脚本默认就行不用改。

**Comment by ghitori** [comment]
> ![88851425-D07D-4F43-8902-04C3EAFF5CFC](https://user-images.githubusercontent.com/23469346/221212319-fc68c449-cb3f-48b9-bbe2-6052c433ee28.jpeg) 使用路由器的可以参考这个，自定义数据文件路径就是我上传的文件，需要放到路由器里，dhcp脚本默认就行不用改。

感谢学长，已在padavan上成功
