### ISSUE TITLE
与最后一次接入区域不符

### ISSUE THREAD

**Issue by lihj0412** [Superfly12138/rjsupplicant#5]
我想在两个地点使用有线网，会提示这个问题。请问该怎么解决呢？是否应该将套餐从电信改成校内？如果用padavan路由器，是否可以选择网络套餐呢？

**Comment by Superfly12138** [comment]
有线网络只能在一个设备使用，没有办法。如果要换地方登录，要在自助服务中心解绑，每次解绑完要冷却7天。这个跟改不改套餐没关系，Padavan应该只有电信可以，别的好像不行。

**Comment by lihj0412** [comment]
> 有线网络只能在一个设备使用，没有办法。如果要换地方登录，要在自助服务中心解绑，每次解绑完要冷却7天。这个跟改不改套餐没关系，Padavan应该只有电信可以，别的好像不行。

如果MAC地址一样就可以。其他人在Windows系统用官方的软件，就可以验证成功，他们是先选择校内那个选项通过验证，然后再改成自己的套餐就可以上网。我想直接在路由器用mentohust命令-S选择套餐，可是现在卡在了-f选择自定义数据文件这一步。提示所选文件/etc/storage/DataPackA.mpf无效。我使用的mentohust命令是-f/etc/storage/DataPackA.mpf。这块儿有什么问题呢？
