### ISSUE TITLE
缺少8021x.exe信息，客户端校验无法继续

### ISSUE THREAD

**Issue by lihj0412** [Superfly12138/rjsupplicant#6]
学长您好，我使用的是padavan中的mentohust命令进行验证，并已经识别到数据文件/etc/storage/DataPackA.mpf，为什么还会提示缺少8021.exe信息呢？

**Comment by Superfly12138** [comment]
参考这个
![78571791-F689-442D-B551-D43EA1241F44](https://user-images.githubusercontent.com/23469346/224215822-16c98d40-b5c9-47fc-8889-4d440de8cf88.jpeg)

**Comment by Superfly12138** [comment]
使用ssh连到路由器，mentohust -b0，看一下输出日志，中文用gbk编码查看。
